[tool.poetry]
name = "anarci"
version = "0.1.0"
description = ""
authors = ["Piotr Deszyński <deszynski@red-sky.pl>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
